version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  target_framework: $(TargetFramework)
  package_id: ArcadeRepo

artifacts:
- path: artifacts/bin/$(package_id)/$(configuration)/$(target_framework)/*.dll
  name: Binary File

before_build:
- nuget restore
  
build_script:
- cmd: Release.cmd

deploy_script:
- cmd: Deploy.cmd
