// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace $(RootNamespace).Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "9f7b718f-0c30-4c9f-92a5-d378853b429b";
        public static Guid Package = new Guid(PackageString);

        public const string PackageMenusString = "0cfb4a3c-2de1-4a08-afde-6f2a32575bc6";
        public static Guid PackageMenus = new Guid(PackageMenusString);

        public const string PackageGroupsString = "0bc60032-f463-4104-a1ad-9bc6a5444c55";
        public static Guid PackageGroups = new Guid(PackageGroupsString);

        public const string PackageCommandsString = "ca1431d8-8fbf-4ba4-b60e-8d0d452c55f6";
        public static Guid PackageCommands = new Guid(PackageCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDM_MENU = 0x0101;
        public const int IDG_GROUP = 0x0011;
        public const int Command = 0x0001;
    }
}
